# Generated by Django 5.1.3 on 2025-01-02 08:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_alter_orderplaced_status_payment_orderplaced_payment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderplaced',
            name='payment',
        ),
    ]
